language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: ZT/Al4ZU7T5510bgmSuFDuxaAiWPhSJAsvj81YDxr93VPCbsPSFwbX3dtUBib7nP2JxXnKObfElhX9AGYV+/PZQXJcUXxZuvNGSlYWtnMhFcrPXhyXnuEK/tt+0EwvuKii0SYgNn61A/bEuytah3/mqT37cpFI9ThSjWZp5VtcYQUL5h2S5HUOUo6rwigqbdd8jJGnRhBxRm93PwRQYz3AxGXW+gz05eLS0b4/dOe46YofZNyxjGxBVtiWPGHSX0KmKpcxxi1cXEIVxLGKK1bZlkGF2blN7LtgAtRK3nBIXEzeMTk1Z2PyoB6c5xfU6RcD1xSmqEk4SaI8oTZp8CHGBSD3k0B1bD5qUwacoRkVe/l6C5Y7n+uhxqQ0NPlNbu466k42M652TKSyNCyDilE31Ae4Xx5w+sQix4VfB8mloXTp8ee++yMiV3cDRr40RliSPso8j4B5HH4HZQh9HfW7hikhOD8NmXfYUhxqvJ6CvChAx9knVKveH8ApFnPo+7jkMGvbd/VbQOpzNQbc3TnkCgt9ogobGUWFYyhIfPa18zhzrGneb0wRAQ0Y2vhxxZeTpHtYY0qVxXkO4jE1bp/uj9QaSYFho0YNP5SKbZqBAkn/A3Q5rbDIYcd17Zeh881QMgPoxFGMnaF61KHWDEDXr+82zPIPTvlfgjh1EM6y4=
