language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: QUlco4V8Gj82dbaVFWg+Py8ZOsw0thz02TAb8x1F2bCAlwgbmN3KW+4KyXix2eElzacfgS8DD0DC1kTroP5ihIx/No14KFz9vsLF5sMqoQcue8ESYMy+qXfDuh174bPxFO2GgtYy/Lol841/rC4px/totSR6u3dAO+xcrijTACKR8w8j8hvBHba7XLl3t1tzzkYBZYMopbhuRo7+jaHhMtbVsXCxde30pD27J6+qWm9GW+pbjK48koXCGRtRxI6WbMK+ME9FQj8MFjP3IUbuyrS5WDLKitnz1vcjbVTdS+8uGfUiFXyIK1U9SV4iZTYlx+QpNLVGEFt7rpwPGFdi72Bv3eC+y9GVBjdccO9PvYzoSzfUIgPjLICbGOHcJrm0PeoGw8qCUs9PWoDpLJtlcxKGGAew80VLHU5/i0PLzDz2N9toNiPqWvbeG6zL+UROKwjozEHtyTdH9lAXdSxBOFPIOoQvb1redhvW8NY7Cbg78l2D2dEZMt6OX08vCImXQMxBpz8AZGl+Fyz7n08fi0h08I6ZiPx3jhxb+1KBhEIwPcR7zx3/FulcXvS8RRA9EoQ6D4I4TFFbhJf2avkZYf23Tb9WJpyG1iYqyERhByjG0df47b5CJ+J3XFnj0fOEihF35w83IHgJpeHzVfvdA44OvFngxRqDPLljdHx0FCM=
  app: obscure-spire-80298
  on:
    repo: synedra/node_deploy
