language: node_js
node_js:
- '7'
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: HNyh3mdcsRy+m5xJUoelHD7TkSiJ/iFPtlKp6njcYrozZ990Icte8ScypSrcdPTFoGCcGeHRObz6AFakNJtivxq9r1+3tVoErKIqKnaCmrOa/u3RcEJZ30yNdzrA8V6ydxW6exfnD7dR+/JqaA1HO9rPnK4qJd3pz5iCuPKQiQlECjPlgJdZvHcX+B+8v4Ad9JEPnLpRaUpgJEthNr1Nbgt3frxUknmnYjtFQY4X1OTmK0+qJX6hOWVpAG3nlW9PgVYNwelhPHSKJ1nWN9tE9wQNjAyeILol2KtyDhqE0t6rmXnlHdLWbAZkFn/SJPBW/ofjEG6PlYUXIIsRuAJ3BCn/G4FYE//fDeMr9GnJT7FrsAZoCHCm1htTp6yX0Bc7uDGw12NLx/Wp3Qa9aCyahwANUUf0WbewCM6HGF1F5QcUluz0z/TGb7oxqam6OynVeUuCcC+d4NMIlbImUUkstGggOQuDNMQqSCe5ExE5BpX39S1xr3qNK2UEirPtnPNSpSMYX/crEbukd0Cpxoe+CYqpDAyoY2NF370sRKc95jbUkmyeRcqfeUEPwb68UhPppGbJU4YV5F0tG2L2bQywY2sLamwq/nLWtgX58onGGRxoBQMtf3Y2xhkWvrNHw28ylUBcg8XNFDZr9RPrrGARl0yEQPdZoNtgO8VL/ihSu/Q=
  app: obscure-spire-80298
  on:
    repo: synedra/node_deploy
