branch-defaults:
  master:
    environment: prod
    group_suffix: null
environment-defaults:
  prod:
    branch: null
    repository: null
global:
  application_name: gametable
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
